### ISSUE TITLE
Dependency on apasel's private btree repo?

### ISSUE THREAD

**Issue by Gankro** [gereeter/btree-rewrite#9]
@apasel422 what's up with that?

**Comment by apasel422** [comment]
It's just a test dependency for benchmarking purposes and can be removed.

**Comment by Gankro** [comment]
Why is the repo private? Can you make it public?

**Comment by apasel422** [comment]
It's not private, actually; it just doesn't exist anymore. If I get some
free time I might try my hand at it again, but once this repo implemented
the majority of functionality, I ended up removing mine.
